import localFont from "next/font/local";
import "./globals.css";


//Components
import Header from "@/components/ui/header";
import PageTransition from "@/components/ui/PageTransition";
import StairTransition from "@/components/ui/stairTransition";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "gem-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>

        <StairTransition  />

        <PageTransition>
        {children}
        </PageTransition>

        
      </body>
    </html>
  );
}
